- id: sfdc
  type: puppet
  groups: [infrastructure_alerting]
  required_for: []
  requires: [infrastructure_alerting]
  parameters:
    puppet_manifest: "puppet/manifests/sfdc.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

