- id: infrastructure_alerting_sfdc
  type: group
  role: [infrastructure_alerting]
  tasks:
    - hiera
    - globals
    - tools
    - logging
    - netconfig
  required_for: [deploy_end]
  requires: [deploy_start]
  parameters:
    strategy:
      type: parallel
